######################################################################
#
# File name : auto_correlation_tb_elaborate.do
# Created on: Tue Apr 15 20:37:45 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.auto_correlation_tb xil_defaultlib.glbl -o auto_correlation_tb_opt
