######################################################################
#
# File name : auto_correlation_tb_wave.do
# Created on: Tue Apr 15 11:53:05 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
