######################################################################
#
# File name : auto_correlation_tb_simulate.do
# Created on: Tue Apr 15 20:37:46 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib auto_correlation_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {auto_correlation_tb_wave.do}

view wave
view structure
view signals

do {auto_correlation_tb.udo}

run 1000ns
