######################################################################
#
# File name : butterfly_tb_wave.do
# Created on: Wed Apr 16 19:29:58 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
