######################################################################
#
# File name : butterfly_tb_elaborate.do
# Created on: Wed Apr 16 19:47:05 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.butterfly_tb xil_defaultlib.glbl -o butterfly_tb_opt
