######################################################################
#
# File name : butterfly_tb_simulate.do
# Created on: Wed Apr 16 19:47:06 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib butterfly_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {butterfly_tb_wave.do}

view wave
view structure
view signals

do {butterfly_tb.udo}

run 1000ns
