#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 01 11:05:09 EDT 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
bin_path="/package/eda2/siemens/questa/cal_2023.4_17.10/questasim/bin"
set -Eeuo pipefail
source test_tb_elaborate.do 2>&1 | tee elaborate.log

