######################################################################
#
# File name : multiply_tb_elaborate.do
# Created on: Thu Apr 17 09:30:25 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.multiply_tb xil_defaultlib.glbl -o multiply_tb_opt
