######################################################################
#
# File name : multiply_tb_wave.do
# Created on: Wed Apr 16 20:46:00 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
