######################################################################
#
# File name : multipy_tb_elaborate.do
# Created on: Wed Apr 16 20:19:52 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.multipy_tb xil_defaultlib.glbl -o multipy_tb_opt
