######################################################################
#
# File name : register_file_tb_wave.do
# Created on: Wed Apr 02 20:43:20 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
