######################################################################
#
# File name : register_file_tb_compile.do
# Created on: Tue Apr 08 10:44:23 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -sv -work xil_defaultlib  "+incdir+../../../../bistatic_radar.srcs/sources_1/new" \
"../../../../bistatic_radar.srcs/sources_1/new/register_file.sv" \
"../../../../bistatic_radar.srcs/sources_1/new/register_file_tb.sv" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

