######################################################################
#
# File name : register_file_tb_simulate.do
# Created on: Tue Apr 08 10:44:24 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib register_file_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {register_file_tb_wave.do}

view wave
view structure
view signals

do {register_file_tb.udo}

run 1000ns
