######################################################################
#
# File name : system_tb_elaborate.do
# Created on: Tue Apr 08 11:26:35 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.system_tb xil_defaultlib.glbl -o system_tb_opt
