######################################################################
#
# File name : system_tb_simulate.do
# Created on: Tue Apr 08 11:26:40 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib system_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {system_tb_wave.do}

view wave
view structure
view signals

do {system_tb.udo}

run 1000ns
