######################################################################
#
# File name : system_tb_wave.do
# Created on: Tue Apr 08 11:11:31 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
