######################################################################
#
# File name : test_tb_elaborate.do
# Created on: Wed Apr 02 18:46:32 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.test_tb xil_defaultlib.glbl -o test_tb_opt
