######################################################################
#
# File name : test_wave.do
# Created on: Tue Apr 01 09:28:28 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
