######################################################################
#
# File name : test_tb_simulate.do
# Created on: Wed Apr 02 18:46:32 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib test_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_tb_wave.do}

view wave
view structure
view signals

do {test_tb.udo}

run 1000ns
