######################################################################
#
# File name : test_simulate.do
# Created on: Tue Apr 01 09:28:28 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib test_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_wave.do}

view wave
view structure
view signals

do {test.udo}

run 1000ns
