######################################################################
#
# File name : test_elaborate.do
# Created on: Tue Apr 01 09:28:23 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.test xil_defaultlib.glbl -o test_opt
