######################################################################
#
# File name : test_tb_wave.do
# Created on: Tue Apr 01 09:36:51 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
