######################################################################
#
# File name : blinky_sv_simulate.do
# Created on: Mon Mar 31 17:42:45 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib blinky_sv_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {blinky_sv_wave.do}

view wave
view structure
view signals

do {blinky_sv.udo}

run 1000ns
