######################################################################
#
# File name : blinky_sv_wave.do
# Created on: Mon Mar 31 17:42:45 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
