######################################################################
#
# File name : blinky_elaborate.do
# Created on: Thu Mar 27 10:55:09 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.blinky xil_defaultlib.glbl -o blinky_opt
