######################################################################
#
# File name : blinky_sv_elaborate.do
# Created on: Mon Mar 31 17:42:43 EDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.blinky_sv xil_defaultlib.glbl -o blinky_sv_opt
